[build]
  base = "MarketBlox7"
  publish = "MarketBlox7"
  functions = "MarketBlox7/netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
