[build]
  base = "MarketBlox7"
  publish = "."
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/checkout"
  to = "/.netlify/functions/checkout"
  status = 200
